image: ubuntu:18.04
variables:
  LC_ALL: C.UTF-8
  LANG: C.UTF-8


format:
  script:
    - apt-get update -qy
    - apt-get install -y python3 python3-dev python3-pip
    - pip3 install pipenv
    - pipenv install --three --pre black
    - pipenv run black --check setup.py stacky tests

typecheck:
  script:
    - apt-get update -qy
    - apt-get install -y python3 python3-dev python3-pip
    - pip3 install pipenv
    - pipenv install --three mypy
    - pipenv run mypy stacky

test:
  script:
    - apt-get update -qy
    - apt-get install -y python3 python3-dev python3-pip
    - pip3 install pipenv
    - make install
    - make test
it:
  script:
    - apt-get update -qy
    - apt-get install -y python3 python3-dev python3-pip
    - apt-get install -y docker.io
    - apt-get install -y curl jq
    - service docker start
    - pip3 install pipenv
    - make install
    - cd it
    - make install
    - make test
